version: '3.8'

services:
  salesgpt-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: salesgpt-backend:prod
    ports:
      - "3000:8080"
    environment:
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_API_TOKEN=${CHROMA_API_TOKEN}
      - CHROMA_TENANT=${CHROMA_TENANT}
      - CHROMA_DATABASE=${CHROMA_DATABASE}
      - EXA_API_KEY=${EXA_API_KEY}
      - ORGANIZATION_API_URL=${ORGANIZATION_API_URL}
      - ORGANIZATION_API_TOKEN=${ORGANIZATION_API_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - API_KEY=${API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/creds/magiq-ai-fc9670291bfe.json
    env_file:
      - .env.prod
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./creds:/app/creds
    networks:
      - salesgpt-network

networks:
  salesgpt-network:
    driver: bridge
